name: cd
on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:

  validate:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.verify.outputs.should_release }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug - Check repository structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          if [ -f "pom.xml" ]; then
            echo "✅ Found pom.xml"
          else
            echo "❌ No pom.xml found"
          fi
      - name: Verify prerequisites
        uses: jenkins-infra/jenkins-maven-cd-action@v1.2.0
        id: verify
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}


  release:
    runs-on: ubuntu-latest
    needs: [validate]
    if: needs.validate.outputs.should_release == 'true'
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Release
        uses: jenkins-infra/jenkins-maven-cd-action@v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
